### ISSUE TITLE
standard compliance (arguable)

### ISSUE THREAD

**Issue by zerobuzz** [ocharles/snap-cors#1]
[http://www.w3.org/TR/cors/#access-control-allow-origin-response-header] sais:

> In practice the origin-list-or-null production is more constrained. Rather than allowing a space-separated list of origins, it is either a single origin or the string "null".

Your code sais:

> | Origins OriginSet
>  -- ^ Allow cross-origin requests from these origins.

I am not sure how to interpret the w3c document, but my bet is that it wants you to use a single origin here, not 0 or more.  What is yours?  (-:

Thanks for writing this!

**Comment by ocharles** [comment]
I'm afraid I'm only providing basic maintenance for this library now, and I honestly can't comment on the intention. However, it at least seems to be doing the right thing! If anyone has any troubles with this and can investigate further, I will accept PRs that clear up the situation.
