### ISSUE TITLE
allow snap <0.15 as snap version constraint (vs current < 0.14)

### ISSUE THREAD

**Issue by cartazio** [ocharles/snap-cors#6]
hey @ocharles, i think snap-cors can reasonably be made to relax that version constraint. Or at the very least things seem to build fine when i --allow-newer=snap to do a test build, and that also enables a much wider range of newer build plans to be possible for applications that depend on snap-cors.

thoughts?

**Comment by ocharles** [comment]
Hey hey. I didn't even know I wasn't up to date with the latest bounds, I'll push them all now. Should be fine.

**Comment by cartazio** [comment]
thanks! 
likewise, a slightly more meta issue is that in the context of the web application i'm helping folks work on, we only depend on snap-core/snap-server otherwise, and depending on snap-cors (which we need) forces us to depend on full snap in all its snaplet glory.  

if you'd be open to shifting the `wrapCORS*` snaplet machinery into a haddock comment for how to do it or something like that (as part of say a major version bump), a colleague of mine would be more than happy to provide the PR

**Comment by ocharles** [comment]
Not sure I understand - are you looking to just shave the dependencies? I'm afraid for that case, I'm not interested in changing the API. If it's because you believe you now have to *use* `snap`, that shouldn't be the case - `applyCORS` should work just fine in a `snap-core` application.

**Comment by cartazio** [comment]
strictly dep shaving.

**Comment by ocharles** [comment]
Yea, I'm afraid I'm not really willing to split this into two libraries, and the `snap` functionality is probably the most idiomatic way of using this library, so I would want to keep that all too. Sorry :(

**Comment by cartazio** [comment]
no worries, figured i'd ask

**Comment by jonpetterbergman** [comment]
Just confirming, snap-cors works fine with snap 0.14.0.2 here.

**Comment by ocharles** [comment]
So this took so long to release - I bumped the bounds and then forgot to actually release anything! This is now on Hackage as 1.2.8.
