### ISSUE TITLE
wrapCORS not working (for me)

### ISSUE THREAD

**Issue by runeksvendsen** [ocharles/snap-cors#8]
Hi there

I have this simple example that I can't get working, and I can't figure out why. The weird thing is that I'm fairly sure it was working fine at some point, but now it doesn't.

Here's the code:

```
main :: IO ()
main = serveSnaplet defaultConfig appInit

appInit :: SnapletInit () ()
appInit = makeSnaplet "ExampleServer" "" Nothing $ do
    addRoutes [
              ("/fundingInfo"
                ,   method GET (writeBS "{'woo' : 8}"))
              ]
    wrapCORS
```

Using `curl` I get the following response:

```
$ curl -i localhost/fundingInfo
HTTP/1.1 200 OK
Server: Snap/0.9.5.1
Date: Thu, 02 Jun 2016 14:37:53 GMT
Transfer-Encoding: chunked

{'woo' : 8}
```

So no CORS headers. What am I missing here?

**Comment by ocharles** [comment]
The best I can suggest is moving `wrapCORS` to be above `addRoutes`. However `wrapCORS` is soon to be removed, so you might be better using `applyCORS`. If this is still a problem, please re-open this issue and I'll try and provide more help.

**Comment by imalsogreg** [comment]
`curl` requests don't contain an `Origin:` header by default. The example should work with an explicit `Origin` header:

```
>> curl -v -H "Origin: http://example.com" localhost:8000/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Origin: http://example.com
>
< HTTP/1.1 200 OK
< server: Snap/1.0.3.1
< access-control-allow-credentials: true
< access-control-allow-origin: http://example.com
< date: Tue, 19 Sep 2017 19:09:14 GMT
< transfer-encoding: chunked
<
* Connection #0 to host localhost left intact
```

Server in ghci:
```
> S.serveSnaplet mempty $ S.makeSnaplet "" "" Nothing $ S.addRoutes  [("", return ())] >> wrapCORS
```

**Comment by ocharles** [comment]
Cheers for the update, Greg - didn't know that! Also, long time no speak - hope you're doing well :smile: :wave:

**Comment by imalsogreg** [comment]
Me neither! I stumbled on this thread in the middle of my own CORS struggles. I'm doing well, hope you are too :) Message me if you're ever in the states again! I live in Baltimore (near Washington DC) now.
